---
image: uberspace/ansible:ansible-2.1

variables:
  SSH_KEY_PATH: /tmp/.ssh-key
  MANUAL_HOST: corona.uberspace.de
  MANUAL_USERNAME: manual
  MANUAL_PATH: /var/www/virtual/$MANUAL_USERNAME/$CI_BUILD_REF_SLUG.$MANUAL_USERNAME.$MANUAL_HOST

stages:
  - build
  - deploy
  - cleanup

before_script:
  - umask 077; echo "$SSH_KEY" | tr -d '\r' > $SSH_KEY_PATH
  - mkdir ~/.ssh && echo $KNOWN_HOSTS > ~/.ssh/known_hosts

  # Dependencies
  - pip install --quiet -r requirements.txt
  - git submodule update --quiet --init --recursive
  - yum install -y centos-release-scl
  - yum install -y git19
  - scl enable git19 bash
  - export PATH=/opt/rh/git19/root/usr/bin:$PATH

Build stable and master manual:
  stage: build
  only:
    - stable
    - master
  artifacts:
    paths:
      - _build
  script:
    - ansible-playbook -v build-stable.yml

Build staging manual:
  stage: build
  except:
    - stable
    - master
  artifacts:
    paths:
      - _build
  script:
    - ansible-playbook -v build-staging.yml
 
Deploy manual to staging:
  stage: deploy
  except:
    - stable
    - master
  script:
    - ansible-playbook deploy-staging.yml 
  environment:
    name: manual/$CI_BUILD_REF_SLUG
    url: http://$CI_BUILD_REF_SLUG.$MANUAL_USERNAME.$MANUAL_HOST
    on_stop: Delete staging manual

Deploy manual to production:
  stage: deploy
  only:
    - stable
    - master
  script:
    - ansible-playbook deploy-stable.yml 
  environment:
    name: manual/$CI_BUILD_REF_SLUG
    url: http://manual.uberspace.de

Delete staging manual:
  stage: cleanup
  when: manual
  script:
    - ansible-playbook destroy.yml
  environment:
    name: manual/$CI_BUILD_REF_SLUG
    action: stop
