---

- name: Build manual
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Clear Sphinx docs
      command: make clean

    - name: Make Sphinx docs
      command: make html
