---

- include: inventory.yml

- name: deploy manual
  hosts: manual
  vars_files:
    - vars.yml
  tasks:
    - name: create document root
      file:
        path: "{{ manual_path }}"
        state: directory

    - name: copy manual to host
      synchronize:
        src: "_build/html/{{ item }}"
        dest: "{{ manual_path }}"
        recursive: yes
        delete: yes
      with_items:
        - en

    - name: create .htaccess
      copy: 
        content: |
          RewriteEngine On
          RewriteRule ^$ /en/ [R]
        dest: "{{ manual_path }}/.htaccess"

    - name: Correct Ownership of DocumentRoot
      file:
        path: "{{ manual_path }}"
        state: directory
        recurse: yes
        mode: 0755
