---

- name: deploy manual
  hosts: all
  vars:
    manual_path: /var/www/virtual/{{ ansible_user }}/{{ lookup('env', 'MANUAL_DOMAIN') }}
  tasks:
    - name: create document root
      file:
        path: "{{ manual_path }}"
        state: directory

    - name: copy manual to host
      synchronize:
        src: "build/html/"
        dest: "{{ manual_path }}/en"
        recursive: yes
        delete: yes

    - name: create .htaccess
      copy: 
        content: |
          RewriteEngine On
          RewriteCond %{HTTPS} !=on
          RewriteCond %{ENV:HTTPS} !=on
          RewriteRule .* https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]
          RewriteRule ^$ /en/ [R]
        dest: "{{ manual_path }}/.htaccess"
        
    - name: symlink analytics
      file:
        src: /var/www/virtual/{{ ansible_user }}/analytics
        dest: /var/www/virtual/{{ ansible_user }}/{{ lookup('env', 'MANUAL_DOMAIN') }}
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: link

    - name: Correct Ownership of DocumentRoot
      file:
        path: "{{ manual_path }}"
        state: directory
        recurse: yes
        mode: 0755
